version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: russian-trading-db-dev
    environment:
      - POSTGRES_DB=russian_trading_dev
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_INITDB_ARGS=--locale=ru_RU.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./russian_trading_bot/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trading-dev-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: russian-trading-cache-dev
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - trading-dev-network

  # Trading Bot Application
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: russian-trading-bot-dev
    environment:
      - ENVIRONMENT=development
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - LOG_LEVEL=DEBUG
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - trading-dev-network
    command: python -m russian_trading_bot.main

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  trading-dev-network:
    driver: bridge