global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Trading bot application metrics
  - job_name: 'russian-trading-bot'
    static_configs:
      - targets: ['trading-bot:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # MOEX API monitoring
  - job_name: 'moex-api-health'
    static_configs:
      - targets: ['iss.moex.com:443']
    metrics_path: '/iss/engines/stock/markets/shares/boards/TQBR/securities.json'
    scheme: https
    scrape_interval: 60s
    scrape_timeout: 30s

  # Russian news sources monitoring
  - job_name: 'news-sources-health'
    static_configs:
      - targets: 
        - 'www.rbc.ru:443'
        - 'www.vedomosti.ru:443'
        - 'www.kommersant.ru:443'
    scheme: https
    scrape_interval: 300s
    scrape_timeout: 30s